Repository rotary-genomics/rotary, pull requests merged in 2024-02, with the labels that each got.

#117 Make repair.py generate repair_info.tsv with linear contigs.
  rotary/repair.py
  rotary/rules/circularize.smk
Labels: bug

#114 Develop lee
  rotary/dataset.py
  rotary/envs/qc.yaml
  rotary/repair.py
  rotary/rotary.py
  rotary/rules/annotation.smk
  rotary/rules/assembly.smk
  rotary/rules/circularize.smk
  rotary/rules/polish.smk
  rotary/rules/qc.smk
  rotary/rules/rotary.smk
  rotary/run.py
  rotary/sample.py
  rotary/utils.py
Labels: enhancement

#122 Install Polypolish via Conda
  rotary/envs/polypolish.yaml
  rotary/rules/polish.smk
Labels: enhancement

#126 Fix coverage summary
  rotary/rules/assembly.smk
  rotary/rules/circularize.smk
  rotary/rules/polish.smk
Labels: bug

#128 Rewrite certain sections of the documentation for improved readability.
  README.md
Labels: documentation

#127 Minor README updates
  README.md
Labels: documentation

#125 Improve read mapping rules
  rotary/config.yaml
  rotary/envs/mapping.yaml
  rotary/envs/masurca.yaml
  rotary/envs/polypolish.yaml
  rotary/rules/annotation.smk
  rotary/rules/polish.smk
Labels: enhancement

#130 Optionally keep final QC reads
  README.md
  rotary/config.yaml
  rotary/rules/qc.smk
Labels: enhancement

#137 Move to using pungi for the sample and snakemake CLI management code.
  README.md
  enviroment.yaml
  meta.yml
  pyproject.toml
  rotary/dataset.py
  rotary/rotary.py
  rotary/rules/qc.smk
  rotary/rules/rotary.smk
  rotary/run.py
  rotary/sample.py
  rotary/stitch.py
  rotary/utils.py
Labels: enhancement

#135 Replace POLCA with pypolca
  rotary/config.yaml
  rotary/envs/pypolca.yaml
  rotary/rules/annotation.smk
  rotary/rules/assembly.smk
  rotary/rules/circularize.smk
  rotary/rules/polish.smk
Labels: enhancement
